version: '3'
services:
  prometheus:
    volumes:
      - ./prometheus.yml:/app/prometheus.yml
    container_name: prometheus
    image: prometheus-server:2.13
    ports:
      - 9090:9090
  grafana:
    container_name: grafana
    image: grafana/grafana:6.4.3
    ports:
      - 3000:3000
  testblack:
    container_name: testblack
    image: testblackbox:latest
    ports:
      - 9115:9115
      - 8080:8080
    volumes:
      - ./:/root/