version: '3'
services:
  redis:
    volumes:
      - /Users/Shared/dockerData/redis:/data #mac
    #     -  :/data #windows
    container_name: redis-4.0.13
    image: redis:4.0.13-alpine3.9
    ports:
      - 6379:6379